name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.MS_GITHUB_TOKEN }}

    - name: Build Docker image with timestamp tag
      run: docker build . --file dockerfile.dev --tag ghcr.io/romanoninag/scaep-armequip-ms:primerpush

    - name: Push Docker image
      run: docker push ghcr.io/romanoninag/scaep-armequip-ms:primerpush

